apiVersion: v1
kind: Service
metadata:
  name: nodeport-backend
spec:
  type: NodePort
  selector:
    app: backend-django
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30080