apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: elastic/kibana:6.4.0
        env:
        - name: SERVER_NAME
          value: "kibana.kubernetes.example.com"
        - name: ELASTICSEARCH_URL
          value: "http://nodeport-elastic.default.svc.cluster.local:9200"
        ports:
        - containerPort: 5601