apiVersion: v1
kind: Service
metadata:
  name: nodeport-elastic
spec:
  type: NodePort
  selector:
    app: elasticsearch
  ports:
  - name: elasticsearch-rest
    nodePort: 30920
    port: 9200
    protocol: TCP
    targetPort: 9200
  - name: elasticsearch-nodecom
    nodePort: 30930
    port: 9300
    protocol: TCP
    targetPort: 9300